### ISSUE TITLE
travis: debug why trusty does not support `go test -race`

### ISSUE THREAD

**Issue by eyJhb** [aau-network-security/haaukins#146]

**Comment by mrturkmen06** [comment]
`go test -v -race ` works on `trusty` image in travis. The branch [travis-trusty-debug-#146](https://github.com/aau-network-security/haaukins/tree/travis-trusty-debug-%23146) uses it. After all, that test command will take place for further pushes when it merged into new version. 

I am closing this issue, if any other concerns appear or something is wrong then issue can be re-opened.

**Comment by eyJhb** [comment]
@mrturkmen06 Remember that it isn't because "it can't run", it just doesn't detect race conditions.

**Comment by mrturkmen06** [comment]
@eyJhb, it actually detects see the build information from [here](https://travis-ci.com/aau-network-security/haaukins/builds/126606805) 

SS: 

<img width="1076" alt="data-race-condition" src="https://user-images.githubusercontent.com/13614433/64637776-ca452e80-d404-11e9-8414-3f666e9b7650.png">

**Comment by eyJhb** [comment]
As long as it does, I just wanted to make that clear! :)
