### ISSUE TITLE
frontend error - cannot unmarshall

### ISSUE THREAD

**Issue by eyJhb** [aau-network-security/haaukins#158]
It should throw a better error, than the following, if you do not have you `frontends.yml`file.

```
unable to create daemon: yaml: unmarshal errors:
  line 7: cannot unmarshal !!str `go-ntp-ova` into store.InstanceConfig
```

**Comment by mrturkmen06** [comment]
I did not see any error while I am working on Haaukins, I thought that this issue opened some time and fixed however forgotten to close. So, it could be very useful for us, if anyone can give confirmation or objection about my statement.

**Comment by kdhageman** [comment]
@mrturkmen06 I think this is fixed, but I am not entirely sure

**Comment by tpanum** [comment]
If we don't even know what the problem is, I assume it is fixed.
