### ISSUE TITLE
Missing form values in case of registration failure

### ISSUE THREAD

**Issue by kdhageman** [aau-network-security/haaukins#182]
When the registration of a team fails, the displayed registration page does not contain the custom fields (see screenshot below) 
![screenshot 2018-11-19 at 15 30 13](https://user-images.githubusercontent.com/6408692/48713224-0b6b1880-ec10-11e8-8500-5b52f1e2000d.png)

**Comment by mrturkmen06** [comment]
Handled with pre-release [1.6.5](https://github.com/aau-network-security/haaukins/releases/tag/1.6.5), not exists anymore.
