### ISSUE TITLE
White screen when pressing connect

### ISSUE THREAD

**Issue by DanielBritze** [aau-network-security/haaukins#188]
When people register and press login, they cannot connect, they only receive a white screen in the new guac tab.
```
Event: | Date | Approx time | Team ID | Type | fix kode | virkede det? | System og browser
Aars HHX | 21/11/2018 | 9:39 | 2d49f2a4 | Guac connect virker ikke | Not avialable | Nej | Macbook air - chrome
Aars HHX | 21/11/2018 | 9:40 | 6c5797ab | Guac connect virker ikke | Not avialable | Nej | Macbook air - chrome
Aars HHX | 21/11/2018 | 9:46 | unkown | Guac connect virker ikke | Not avialable | Nej | Macbook - chrome
Aars HHX | 21/11/2018 | 9:45 | bed5a209 | Guac connect virker ikke | Not avialable | Nej | Macbook - safari
Aars HHX | 21/11/2018 | 9:45 | 5f32a235 | Guac connect virker ikke | Not avialable | Nej | Macbook - chrome
Aars HHX | 21/11/2018 | 9:50 | ef89a5e6 | Guac connect virker ikke | Not avialable | Nej | Macbook - chrome
Aars HTX | 21/11/2018 | 12:30 | -- | Guac connect virker ikke |   |   | acer- windows chrome
Aars HTX | 21/11/2018 | 12:30 | teamscm | Guac connect virker ikke |   |   | Asus - windows - chrome
```

**Comment by mrturkman** [comment]
Hi, 

This might me delayed observation regarding to white screen, nevertheless I wanted to share what I found regarding to "white screen " issue. 

When a user connected to Haaukins platform over Google Chrome browser and click "Connect" button, they face "White screen" as you described. However, it does not happen in other browsers such as Safari & Firefox.  SS of the logs given below when an user tried to connect platform over Chrome. 
![Screenshot 2019-07-17 at 11 51 29](https://user-images.githubusercontent.com/13614433/61366147-50bc1480-a889-11e9-928d-ef2dcf57a890.png)

So, I think, the issue (if it does not happen in other browsers (Firefox, Safari) ) is related with the dependent library *(Guacamole), which enables users to connect Kali over browser by creating RDP.  All in all, there might be some misconfiguration within Go files or another bug, it will be discovered and solved. This is just an observation from log files and tests on other browsers, other inspections might take place regarding to white screen issue. 

Regards.

**Comment by tpanum** [comment]
Without having time to prove it, I have strong suspicion that it is linked to the interception module. I suffer from the same issues when trying from Firefox 67.

**Comment by jbjjbjjbj** [comment]
I may be wrong but i think it has something to with users not getting a guac account on registration.

When a users registers on ctfd the registration [hook function](https://github.com/aau-network-security/haaukins/blob/master/event/event.go#L286) exist early if no labs are available at the moment.

Therefore their account will never be assigned to a guac account, and [guacLoginIntercept](https://github.com/aau-network-security/haaukins/blob/master/svcs/guacamole/intercept.go#L106) will return without writing anything resulting in white screen.

This can also be seen with the debug prints added below.

![image](https://user-images.githubusercontent.com/16254971/62944731-a11d8800-bddd-11e9-8861-bf7a2e6d97ee.png)

Here team ac96a011 registers and gets an lab and RDP connection.
However team 2b3cb84a hits the intercept but doesn't get an guac account.
Later when a new vm is added team 2868f4e9 is able to connect.

**Comment by mrturkmen06** [comment]
So, basically if there is no VM ready to assign, it creates whitescreen error, hence some queuing of VMs and some information while VMs are initialised might be shown on CTFd side as I explained  in here [white-screen-fix](https://github.com/aau-network-security/haaukins/blob/white-screeen-fix/lab/hub.go) at line 150.

**Comment by mrturkmen06** [comment]
@jbjjbjjbj development on white screen issue fixed, users will not face white screen, they will face waiting screen until they assigned to a lab.
