### ISSUE TITLE
Certificate issuance fails because of failed DNS lookup

### ISSUE THREAD

**Issue by kdhageman** [aau-network-security/haaukins#203]
Haaukins uses `certmagic` with a DNS challenge for automatic TLS certificate renewals. However, the DNS lookup for the specific DNS record (`TXT` for `_acme-challenge.<domain>`) fails. 

A manual fix seems to be to change the default Cloudflare name server `1.1.1.1` (i.e. Cloudflare) to the public Google one (`8.8.8.8`), because those resolvers resolve the record correctly.

Permanently changing the DNS resolver does not seem an elegant solution to this problem though.

**Comment by mrturkmen06** [comment]
Haaukins does not use certmagic anymore, therefore this issue is also vanished.
