### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by JensMyrup** [aau-network-security/haaukins#210]
We often/sometimes need to restart the server due to memory leakage from virtual machines not shutting down properly.

**Comment by mrturkmen06** [comment]
- When stop command executed, just containers  closed, VMs continue to run, it might be the intention at the beginning however shutting down the VMs could be useful in order to use resources properly. So, closing VMs will take place...

**Comment by mrturkmen06** [comment]
Memory leakage from virtual machines which do not shut down properly, problem has been solved.
