### ISSUE TITLE
Use go modules for managing versions of dependencies

### ISSUE THREAD

**Issue by kdhageman** [aau-network-security/haaukins#211]

**Comment by mrturkmen06** [comment]
Go modules integrated into Haaukins, however there is a problem with a package and actually it is declared on golang wiki page over [here](https://github.com/golang/go/wiki/Modules#how-can-i-resolve-parsing-gomod-unexpected-module-path-and-error-loading-module-requirements-errors-caused-by-a-mismatch-between-import-paths-vs-declared-module-identity)

**Comment by mrturkmen06** [comment]
integrated to version [1.6.4](https://github.com/aau-network-security/haaukins/releases/tag/1.6.4)
