### ISSUE TITLE
Implementation of Monitoring platform 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#213]
Hi, 

It will be quite useful to implement monitoring platform over Haaukins in order to understand which resources are heavily used. In addition,  it can give interactions of systems which are running in background. According to extracted information from monitoring tools, we can have solid idea which actions should be taken for the system. Furthermore, trigger system with help of monitoring tools can be configured too. 

Regards.

**Comment by kidmose** [comment]
Setting up some monitoring on the the health of the virtualisation/hosting platform seems highly relevant for addressing issues like #210 .

**Comment by mrturkmen06** [comment]
Partially done with Datadog agent which runs on sec02. Now, we have logs which is gathered from haaukins service and monitoring option for server & containers. I have tried to invite you to datadog page. If I forgot to invite you to datadog and you are interested with it,  please send a message to me that I can invite you.

**Comment by mrturkmen06** [comment]
do you think, it is enough such a monitoring environment to close this issue ? @kidmose  (I am a little bit in doubt)  


<img width="1480" alt="Host & Docker metrics" src="https://user-images.githubusercontent.com/13614433/65819005-add42f00-e217-11e9-80eb-8ad9537eeb18.png">

**Comment by kidmose** [comment]
I think this meets our needs for insights into anomalous resource consumption, and it will even alert on it too. 
I'm sure this is sufficient for now :+1:
Nice work.

**Comment by mrturkmen06** [comment]
Closing issue, since Datadog meets our needs, for now. Could be reopened in future.
