### ISSUE TITLE
Add functionality to pin a certain docker image version

### ISSUE THREAD

**Issue by kdhageman** [aau-network-security/haaukins#221]
I can foresee problems ocurring when Guacamole introduces non-backwards compatible changes in a new release. So preferably, we would be able to set a specific version of Guacamole Docker images to be used.

**Comment by mrturkmen06** [comment]
This issue can be handled after following issue is done >  #223 (Integrating WEBUI to private docker registery). Also, there should be explicit declaration of "private registry" specs, such as which port it uses (I assumed it uses 5000 however I failed to connect port 5000 on sec01).

**Comment by mrturkmen06** [comment]
The main reason of proposing such a statement is that  we can easily change other docker images versions if we have such a webui. No need to interact with server. (over ssh )

**Comment by mrturkmen06** [comment]
All images stored on our private registry so there is no need to put a specific version since those images will not be updated automatically. As for as I see, we do not pull any docker image from official docker hub, hence I am closing the issue, however if there are other concerns regarding to this issue, it can be opened.

**Comment by kdhageman** [comment]
@mrturkmen06 I realise that we do pull from Docker Hub in some cases (e.g. https://github.com/aau-network-security/haaukins/blob/master/svcs/dhcp/dhcp.go#L52)

**Comment by mrturkmen06** [comment]
Ok, I can pin versions on them however there is no explicit version for the current ones that we are using, how should I decide which version to use ?

**Comment by mrturkmen06** [comment]
versions added
