### ISSUE TITLE
Deletion of all resources to an event 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#225]
There are some situations that we might need to delete all resources belong to an event, for instance sometimes events are created for only particular meeting, demonstration and etc, at this point it might be good idea to remove all instances of that event and keep one main endpoint such as (beta.ntp-event.dk), closing events does not remove resources of VMs and dockers.

**Comment by mrturkmen06** [comment]
It is interesting found that even we close the event the associated link resides for example I have created test.ntp-event.dk and close it. Even it is closed the domain accessible, I think it is not normal behaviour. Am I right @kdhageman ?

**Comment by kdhageman** [comment]
> It is interesting found that even we close the event the associated link resides for example I have created test.ntp-event.dk and close it. Even it is closed the domain is accessible, I think it is not normal behaviour. Am I right @kdhageman ?

I am not sure I fully understand, so please confirm if this is correct: you create an event (named `test`) and afterwards close it? And you observed that the webpage (`test.ntp-event.dk`) is still available after closing it? If that is indeed the situation, this should not happen.

**Comment by mrturkmen06** [comment]
Yeah, that's the case, unfortunately .

**Comment by kdhageman** [comment]
As discussed, the `404` page is expected behavior, so I am closing this issue
