### ISSUE TITLE
Create a logo for the project

### ISSUE THREAD

**Issue by tpanum** [aau-network-security/haaukins#231]
As the platform expands, it might be nice to have a logo so users of the platform can quickly recognize the platform.

**Comment by mrturkmen06** [comment]
Is this issue different than #202 ?

**Comment by tpanum** [comment]
In theory no, however, we might move away from CTFd in the future. So I guess this proposal is slightly more generic.

**Comment by mrturkmen06** [comment]
👍🏻

**Comment by tpanum** [comment]
![haaukins_proposal](https://user-images.githubusercontent.com/1385692/63269018-bd19a180-c295-11e9-9679-51e9117067bd.png)

This is a proposal.

**Comment by mrturkmen06** [comment]
[https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A0be0be9d-0a57-4357-b1c4-8f312f19a9d1](Haaukins Logo Suggestion)

**Comment by tpanum** [comment]
Looks amazing! Who created those?

**Comment by mrturkmen06** [comment]
my brother :)

**Comment by mrturkmen06** [comment]
Created and adapted to master branch with release of 1.6.4
