### ISSUE TITLE
Display created time for events (in: event list)

### ISSUE THREAD

**Issue by tpanum** [aau-network-security/haaukins#239]
Displayed the creation time of a certain event within `hkn event list`

**Comment by mrturkmen06** [comment]
Hi Thomas, 

I have added it, the representation of the time as shown below, I used startedtime value from event file [here](https://github.com/aau-network-security/haaukins/blob/795b326059c70a153175626cadb60cd1ddc8721e/store/event.go#L38).

**Comment by tpanum** [comment]
Looks super nice. Great work, @mrturkmen06

**Comment by mrturkmen06** [comment]
added to [white-scree-fix-minor branch](https://github.com/aau-network-security/haaukins/tree/white-scree-minor-fix), if we merge it into 1.6.0 branch then we can deploy it as well with the minor fix on white screen issue.

**Comment by mrturkmen06** [comment]
Although this feature is added into 1.6.3, there will be some other changes regarding to it, since this task is belong to version 1.7.0, the issue will remain open until 1.7.0 is released. When refactored lab.Hub took place in version 1.7.0, this issue can be closed at that time.

**Comment by mrturkmen06** [comment]
exists in new release [1.6.4](https://github.com/aau-network-security/haaukins/tree/1.6.4)
