### ISSUE TITLE
lab.Hub requires refactoring

### ISSUE THREAD

**Issue by tpanum** [aau-network-security/haaukins#242]
`lab.Hub` is a fairly complex interface (and its related struct). It needs to be simplified, and the code needs to be reworked.

#230 did not fix the lab assignment issue, and ended up being more of a funky wrapper around a poorly written `lab.Hub` (originally created by me, but occasionally time is limited).

**Comment by mrturkmen06** [comment]
adapted to [1.6.4](https://github.com/aau-network-security/haaukins/releases/tag/1.6.4)
