### ISSUE TITLE
team based flag arrangement 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#262]
In current version of Haaukins, dynamic flags are generated for per event, it might be better if we have dynamic flags per team. In this case, static flags might be removed or modified, it is debatable topic. 

Any proposal, comment and complain are always welcome !

**Comment by eyJhb** [comment]
Aren't they currently based on pr. team? That was the hole idea to begin with, that teams couldn't share flags with each other

**Comment by mrturkmen06** [comment]
Apparently, it is not.

**Comment by mrturkmen06** [comment]
Update:  the functions which are responsible for checking flags per team was malfunctioning, that's why I thought there is no implementation of team based flag arrangement. However, with quick fix to that issue [Dynamic flags not functioning as intended #190](https://github.com/aau-network-security/haaukins/issues/190), we regain team based flag arrangement functionality.

**Comment by mrturkmen06** [comment]
After having merge the branch [fix-dynamic-flags-#190](https://github.com/aau-network-security/haaukins/tree/fix-dynamic-flags-%23190) into 1.6.4 branch, this issue will be closed.

**Comment by mrturkmen06** [comment]
Closing issue, with refactored  lab.hub, this issue is not exist anymore.
