### ISSUE TITLE
Better logging environment for Haaukins 

### ISSUE THREAD

**Issue by mrturkmencom** [aau-network-security/haaukins#270]
In current situation, Haaukins logs all information to daemon.log with other services that sec02 has and logs are not standardised, hence JSON formatted logs should  be introduced  to Haaukins platform.

**Comment by kidmose** [comment]
Is it possible to use some established logging framework in the code?
 - Something that can be configured, avoiding hardcoding that JSON is used? (Maybe this is obvious :) )

**Comment by mrturkmen06** [comment]
Yeah, it is possible, actually existing logging framework is capable of making logs in JSON format, so we can keep use it by specifying general skeleton (format).
