### ISSUE TITLE
Integrate github actions into Haaukins project

### ISSUE THREAD

**Issue by mrturkmencom** [aau-network-security/haaukins#287]
**Is your feature request related to a problem? Please describe.**
Not exactly, will add ability to test and deploy all binaries with Github's CI. 
- [x] Run test cases
- [x] Build binaries
- [ ] Release 
- [ ] Deploy [could be]

**Comment by mrturkmen06** [comment]
deployment phase left can be observed [github-actions-test](https://github.com/aau-network-security/haaukins/tree/github-actions-test)
