### ISSUE TITLE
Link to hack.aau.dk from frontpage of events gives error

### ISSUE THREAD

**Issue by JensMyrup** [aau-network-security/haaukins#318]
Following the link gives a "This Connection is Not Private" error. Guess it is something with certificate of hack.aau.dk - then Per Mejdahl will be the one who can help out.

**Comment by mrturkmen06** [comment]
Updated with https://www.facebook.com/groups/957517617737780, 

however I think, group id could be changed into text  like https://www.facebook.com/groups/aauhackers or something else which is easy to remember ! 

Now, the link is updated on CTFd site but will be available when we restart Haaukins or create new event.
