### ISSUE TITLE
Merge `the_real_amigo` for the new Haaukins

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins#361]
The `the_real_amigo` has been created to refactor haaukins architecture. The new frontend has been developed and ctfd removed, moreover the yml are not used anymore as event file because a new microservice has been created https://github.com/aau-network-security/haaukins-store.

In order to make the new haaukins available some more steps are required:
- fix tests and create new ones #362 
- re-create keylogger function #363 
- make documentation for new haaukins architecture and haaukins-store #364 
- test new haaukins in the test server

**Comment by mrturkmen06** [comment]
I think, this is leftover, so we can actually take this issue into done as well. 

- Basically, for time being, amigo will not run on its own branch, for now, then it will be migrated to master after some real scenario testing.
