### ISSUE TITLE
deployment for develop-a branch

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#375]
Currently, we are going to test Haaukins amigo on our dev server, the changes for deployment step could be nice to have to development server instead production one. 
Todo List: 

- Change deployment step to development server for `develop-a` branch
- Ensure permissions are granted correctly
- Make sure that renewing certificates in docker environment running for the dev server domains.

**Comment by mrturkmen06** [comment]
This is done in commit https://github.com/aau-network-security/haaukins/commit/10f96c59a6e487aeaf932df761cd4b7faa6d5bf6 , and necessary keys inserted into development server, I am closing it now, if something goes wrong, it could be opened. 

- The only thing to be careful about is tagging commits, the ordinary haaukins releases has tag of `*.*.*` but the releases which includes amigo in it should include `v*.*.*`

**Comment by gianmarcomennecozzi** [comment]
Seems that all the steps in this challenges has been done. You can close the issue. :)
