### ISSUE TITLE
preparation for development server

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#376]
- [x] remove dummy data from amigo
- [x] change the docker file test and run tests again (the tests dont have to delete the content of the DB)
- [x] make database admin page  secure
- [x] change ports to default values (80,443)
- [x] check problem with ssl redirect
- [x] make haaukins run a service on dev server.

**Comment by mrturkmen06** [comment]
- On sec02, Registery is running on default ports which means, the docker-compose should be modified -(with reverse proxy setting)- in order to make Haaukins available with redirection. 

-  Note that, in order to run Haaukins with amigo web frontend, index templates should be placed into `<path-to-service-file>/svcs/amigo/`, unnecessary files (other than templates) could be deleted in svcs . (when binary file is used) 

- There is no problem regarding to redirection from HTTP to HTTPS in Haaukins side, it creates issue due to running nginx docker container in default ports.

**Comment by gianmarcomennecozzi** [comment]
thanks for the information. all the steps have be developed so I am closing this issue
