### ISSUE TITLE
Direct integration between platform and learning materials

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins#383]
This features will give the possibility for users to interact with Haaukins from a link provided in the learning materials page. The user should be able to connect to Guacamole and solve the challenges related to the learning material page in which was the link.

The Idea is to create an API in Haaukins that accept as input the challenges tag and create an instance of Guacamole in which the challenges are running. A loading page will be showed to the user while an instance is created and ones is done the user will be redirected to Guacamole. Moreover Haaukins should expose a second api used to solve challenges

A form will be created below the link provided in the learning materials in order to send requests to the API to check if the flags are correct.

**Comment by gianmarcomennecozzi** [comment]
@mrturkmen06 Any suggestions are more than welcome :smile:

**Comment by mrturkmencom** [comment]
It is separated from haaukins repository, now it has it is own repo called [haaukins-api](https://github.com/aau-network-security/haaukins-api).
