### ISSUE TITLE
private registry for docker containers is down

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#400]
**Describe the bug**
Since server 1 is started to used for development/production (time to time), it is not possible to run registry on port 80, which means, pulling docker images from private registry fails which is not good and useful. For this reason this issue should be fixed. 

**To Reproduce**
1. Remove all local images which are starting with `registry.sec-aau.dk/...`
2. Try to run an event. 
3. Pulling docker image will fail , see the error.

**Expected behavior**
There should not be any failure on pulling docker images.

**Comment by mrturkmen06** [comment]
Docker registry moved to claaudia, I am not sure how it will be stable at the moment. However, I have redeploy all challenges which are exist on Gitlab using continues integrations (CI), meanwhile I noticed that we have new challenges thanks to @Mikkelhost , I think, we may need to prepare CI for them and deploy, to registry. I hope, nothing will go wrong regarding to claaudia.

**Comment by mrturkmen06** [comment]
The issue seems solved,  however I will keep the issue open for few days just to be sure how it will react. There should NOT be any warning on pulling images. 

FYI @gianmarcomennecozzi

**Comment by gianmarcomennecozzi** [comment]
Thanks for solving this problem. Let's keep open this issue open for a couple of days while we are testing. Regarding the new challenges made bu Mikkel, we should create CI.

**Comment by mrturkmen06** [comment]
It's been two weeks and there is nothing wrong with private registry. Hence, I am closing the issue.
