### ISSUE TITLE
VPN solution to access to labs

### ISSUE THREAD

**Issue by mrturkmencom** [aau-network-security/haaukins#418]
Event based VPN solution should be introduced which means that users who would like to use haaukins in their environment should be able to access from anywhere using VPN credentials.

**Comment by mrturkmen06** [comment]
For implementation of VPN solution, going further with [wireguard](https://www.wireguard.com) makes much more sense than openvpn, according to feedback of others. Which lead to integration of VPN into project  :)

**Comment by mrturkmen06** [comment]
Quite interesting document and includes crucial information about conterication of network, I think, this one is the right way to go for encrypted VPN solution [check this out](https://www.wireguard.com/netns/#ordinary-containerization)

**Comment by mrturkmencom** [comment]
Under test on https://beta.ntp-event.dk

**Comment by mrturkmencom** [comment]
closed #478
