### ISSUE TITLE
Lab error (waiting page forever)

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins#429]
**Describe the bug**
guacamole remains in waiting page forever

**To Reproduce**
Create an event and immediately signup to the event

**Additional context**
If you try to restart the lab from the WebClient it will give u the following error `Lab is nil, no lab found for given team id ! `

Screenshot below
![Screenshot from 2020-07-03 15-19-18](https://user-images.githubusercontent.com/55431233/86473182-bb878980-bd40-11ea-97fe-ff28e2692bb8.png)

**Comment by mrturkmencom** [comment]
#454  similar issue
