### ISSUE TITLE
Unable to get teams from the store after i restart haaukins

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins#430]

**Comment by gianmarcomennecozzi** [comment]
This might be already fixed when we deploy the new changes made @mrturkmencom

**Comment by mrturkmencom** [comment]
The problem is not about getting teams instead the problem is that when haaukins restarted, it is not possible to login with existing credentials of users who are registered from event page.

**Comment by gianmarcomennecozzi** [comment]
Error fixed in this PR 25dc39be79b57a7b53e4466541df9736e4bf70e5
