### ISSUE TITLE
Clipboard Integration -- Feedback from IT CPH University 

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins#450]
Users are having bad experience in copy and paste stuff from their OS to Kali Linux.

- [x] In the haaukis home page we can add some important information of how to deal with the copy and paste scenario.

- [ ] We might try to see if there is a better approach of how to copy and paste stuff

**Comment by mrturkmencom** [comment]
Yeah, sure, for quick solution, providing guideline how to deal with those situation could be nice. Basically, we can document them respect to documentation of guacalome regarding to copy/paste functionality.
