### ISSUE TITLE
Delete Team Option

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins#453]
Its possible to notice from the logs and from the feedback got that people use to create a new team every time their VM crash or dosent work. In order to avoid it problem and improve the performance on the server it would be nice to have the option to delete a team from an event

Its a good way to start dealing with haaukins since it will not be much to add. it just:

- add a new message in the proto file

- make deleteTeam function 

- implement the features in the webclient and the client

**Comment by mrtrkmn** [comment]
This issue has been released already https://github.com/aau-network-security/haaukins/pull/643
