### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins#474]
With the increasing amount of people using Haaukins, we need more rules on the management side of the events. Therefore user priviledges need to be clarified and developed into Haaukins. The 3 kind of user type that we have at the moment are good but some improvements can be done.

- [ ] All users are non priviledges (Define how many events and lab they can create)

- [ ] Priviledge can create more events moreover can manage all the event including suspend and resume functionalities

- [ ] Sudoers have all the priviledges

**Comment by mrtrkmn** [comment]
Mostly implemented, detailed user management might require to have proper RBAC  system. Considering current needs, it is not a consideration.
