### ISSUE TITLE
remove unintentionally forgotten domain address

### ISSUE THREAD

**Issue by mrturkmencom** [aau-network-security/haaukins#535]
Pass domain address from daemon config.

https://github.com/aau-network-security/haaukins/blob/6836c7ae1244392467bd000ab28eb2a515ac0584/svcs/guacamole/event.go#L314

**Comment by Lanestolen** [comment]
I think this one can be closed, fixed in #536

**Comment by mrturkmencom** [comment]
#536 and 9bbdf0b461002d84d3999d03760da5a208a9e833
