### ISSUE TITLE
Inform users about sleep mode

### ISSUE THREAD

**Issue by JensMyrup** [aau-network-security/haaukins#538]
After not being active in the virtual lab for a while it goes to sleep. 

If the user remains logged in during this and then tries to reconnect, then he cannot connect: Logging out and then in again solves the issue because the login wakes up the lab. Can we inform the user about this, e.g. as part of the signup information?

**Comment by mrturkmencom** [comment]
#539

**Comment by mrturkmencom** [comment]
Done with commit 1d93787
