### ISSUE TITLE
Add reverse DNS lookup possibility

### ISSUE THREAD

**Issue by Mikkelhost** [aau-network-security/haaukins#574]
**Is your feature request related to a problem? Please describe.**
As we get more challenges and alot of them are web applications, we have started to give them all Domain names.
However when you do an nmap scan it isn't possible to do the reverse DNS lookup on the IP.
This will make it hard to distinguish the challenges where you need nmap against the ones that don't.
Where the ones that aren't intended for nmap has a domain assigned.

**Describe the solution you'd like**
Somehow make it possible to do a reverse DNS lookup, by enabling PTR i guess?

**Describe alternatives you've considered**
Can't really think of an alternative

**Comment by mrtrkmn** [comment]
This is possible with `/etc/hosts` file. Hosts information of each team has been added to hosts tab inside the event. Whenever users copy the hosts information to their environment's  hosts file, reverse DNS lookup will be available to use.
The hosts information has been merged to master, when new release came up. It can be used under production environment.

**Comment by mrtrkmn** [comment]
Released with [2.4.0](https://github.com/aau-network-security/haaukins/releases/tag/2.4.0)
