### ISSUE TITLE
Web admin - small fixes

### ISSUE THREAD

**Issue by JensMyrup** [aau-network-security/haaukins#591]
In web admin, there are some small annoyances:
- event tags must be non-capital letters. Can we check that?
- Even when selecting VPN mode, you still have to choose a frontend. Maybe it makes more sense to choose "VPN" instead of Kali or Kali-updated?

**Comment by mrtrkmn** [comment]
Fixed https://github.com/aau-network-security/haaukins-webclient/commit/407b238a369decf285871446dedcdf7b364007d7
