### ISSUE TITLE
When signing up: Different password lengths

### ISSUE THREAD

**Issue by JensMyrup** [aau-network-security/haaukins#603]
Currently there is a password limit on the first password line (20 characters), but this limit does not apply on the second line. Some people don't understand this error, so maybe a good idea to have the same limit in both places, and also state that there is a password limit of 20 characters (if this is the case).

**Comment by mrtrkmn** [comment]
#604

**Comment by mrtrkmn** [comment]
Both password and repeat of the password requires 20 chars at max on signup page. (Thanks to @Lanestolen #604 )
