### ISSUE TITLE
Remove white space around flags

### ISSUE THREAD

**Issue by Lanestolen** [aau-network-security/haaukins#613]
**Is your feature request related to a problem? Please describe.**
In some of the exercises there can be spaces before or after the flag when copied, so when people tries to insert the flag it returns invalid flag.

**Describe the solution you'd like**
I think that the validateflag function could be changed to remove potential white space around the flags.

**Describe alternatives you've considered**

**Additional context**

**Comment by mrtrkmn** [comment]
Fixed e04897a1b704504b499dfaccbbce14e70ba22242
